config/routes.rb
Rails.application.routes.draw do
  resources :procedures_projects
  resources :pratices_procedures
  resources :pratices
  resources :procedures
  get 'home/index'
  root 'home#index'
  resources :member_roles
  resources :teams
  resources :roles
  resources :members
  resources :projects do
      collection do
        get 'index_audit'
        get 'index_unconformities'
      end
    resources :audits do
     resources :unconformities do
       resources :corrective_actions
     end
    end
  end
  
  

end

app/models/audit.rb
class Audit < ActiveRecord::Base
    validates :identification, :description, :datetime, :schedule, presence:true
	KIND = %w(Produto Processo)
	validates_inclusion_of :kind, in: KIND
  belongs_to :projetc
  has_many :unconformities, dependent: :destroy
  
end

app/models/corrective_action.rb
class CorrectiveAction < ActiveRecord::Base
  validates :name, :description, presence: true
	validates_length_of :description, maximum: 200

	belongs_to :unconformity
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :member_roles
end

app/models/member_role.rb
class MemberRole < ActiveRecord::Base
  belongs_to :member
  belongs_to :role
  belongs_to :team
  has_many :projects, through: :team
end

app/models/pratice.rb
class Pratice < ActiveRecord::Base
  has_many :pratices_procedures, dependent: :destroy
  has_many :procedures, through: :pratices_procedures
end

app/models/pratices_procedure.rb
class PraticesProcedure < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :pratice
  has_many :pratices_procedures_projects
  has_many :projects, through: :pratices_procedures_project
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  validates :name, :description, presence:true
  
  has_many :pratices_procedures, dependent: :destroy
  accepts_nested_attributes_for :pratices_procedures,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :pratices, through: :pratices_procedures
  accepts_nested_attributes_for :pratices,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :procedures_projects
end

app/models/procedures_project.rb
class ProceduresProject < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :client, :date_ready, :description, presence:true
  has_many :audits,  dependent: :destroy
  has_one :team , dependent: :destroy
  accepts_nested_attributes_for :team
  
  has_one :procedures_project, dependent: :destroy
  accepts_nested_attributes_for :procedures_project,
  reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :member_roles
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :project
  has_many :member_roles, dependent: :destroy
  has_many :members, through: :member_roles
  has_many :roles, through: :member_roles
  
  accepts_nested_attributes_for :member_roles,
  reject_if: :all_blank, allow_destroy: true
  
end

app/models/unconformity.rb
class Unconformity < ActiveRecord::Base
  validates :name, :description, presence:true
  belongs_to :audit
  has_one :corrective_action, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pratices_controller.rb
class PraticesController < ApplicationController
  before_action :set_pratice, only: [:show, :edit, :update, :destroy]

  # GET /pratices
  # GET /pratices.json
  def index
    @pratices = Pratice.all
  end

  # GET /pratices/1
  # GET /pratices/1.json
  def show
  end

  # GET /pratices/new
  def new
    @pratice = Pratice.new
  end

  # GET /pratices/1/edit
  def edit
  end

  # POST /pratices
  # POST /pratices.json
  def create
    @pratice = Pratice.new(pratice_params)

    respond_to do |format|
      if @pratice.save
        format.html { redirect_to @pratice, notice: 'Pratice was successfully created.' }
        format.json { render :show, status: :created, location: @pratice }
      else
        format.html { render :new }
        format.json { render json: @pratice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pratices/1
  # PATCH/PUT /pratices/1.json
  def update
    respond_to do |format|
      if @pratice.update(pratice_params)
        format.html { redirect_to @pratice, notice: 'Pratice was successfully updated.' }
        format.json { render :show, status: :ok, location: @pratice }
      else
        format.html { render :edit }
        format.json { render json: @pratice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pratices/1
  # DELETE /pratices/1.json
  def destroy
    @pratice.destroy
    respond_to do |format|
      format.html { redirect_to pratices_url, notice: 'Pratice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pratice
      @pratice = Pratice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pratice_params
      params.require(:pratice).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pratices_helper.rb
module PraticesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/pratices/_form.html.erb
  <%= form_for([@pratice]) do |f| %>
  <%= render '/layouts/errors', object: @pratice %>
  
    <div class="form-group">
      <%= f.label :Nome %><br>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :Descrição %><br>
      <%= f.text_area :description, class:"form-control"%>
    </div>
      </br>
      <%= f.submit class:'btn btn-primary' %>
      <%= link_to 'Cancelar', pratices_path(@pratice), class:'btn btn-default' %>
  <%end%>

app/views/pratices/edit.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading"><h2><%= "Editando #{@pratice.name}"%></h2></div>
      <div class="panel-body">
        <%= render 'form'%>
      </div>
  </div>
</div>

app/views/pratices/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="pagee-header"><%= pluralize(@pratices.size, "Prática", "Práticas") %> 
				<small class="novo_projeto"><%= link_to new_pratice_path, class:'btn btn-default' do %> Nova Prática
				<%end%></small>
			</h1>
		</div>
	</div>

		<div class="panel panel-default">
		 	<% @pratices.order("name").each do |pratice| %>
				<div class="row">
					<div class="col-md-7">
						<ul>
							<p><%= link_to pratice.name , pratice%></p>
						</ul>
					</div>
				</div>
			<% end %>
	  </div>
</div>

app/views/pratices/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading"><h2><%= "Criar Prática"%></h2></div>
      <div class="panel-body">
        <%= render 'form'%>
      </div>
  </div>
</div>

app/views/pratices/show.html.erb
<div class="container">
	<div class="jumbotron">
		<article>			
			<header>
				<h1><%= @pratice.name %></h1> 			
			</header>
			<hr>
				<div class="panel-body">
					<h3>Descrição</h3>
						<div class="panel panel-default">
							<p style= "text-align: justify;"><%= simple_format @pratice.description%></p>
						</div>
				</div>
		</article>
		<hr>
		<%= link_to edit_pratice_path(@pratice), class:'btn btn-default' do %>
		 		<i class="glyphicon glyphicon-edit">Editar</i>
			<%end%>

		<%= link_to "Deletar Prática", pratice_path(@pratice),method: :delete, data:{ confirm: "Deseja deletar este Processo?"}, class:'btn btn-default'%>
		
		<%= link_to "Votlar", pratices_path(@pratice), class:'btn btn-default'%>
	</div>
 </div>