config/routes.rb
Rails.application.routes.draw do
  resources :procedures_projects
  resources :pratices_procedures
  resources :pratices
  resources :procedures
  get 'home/index'
  root 'home#index'
  resources :member_roles
  resources :teams
  resources :roles
  resources :members
  resources :projects do
      collection do
        get 'index_audit'
        get 'index_unconformities'
      end
    resources :audits do
     resources :unconformities do
       resources :corrective_actions
     end
    end
  end
  
  

end

app/models/audit.rb
class Audit < ActiveRecord::Base
    validates :identification, :description, :datetime, :schedule, presence:true
	KIND = %w(Produto Processo)
	validates_inclusion_of :kind, in: KIND
  belongs_to :projetc
  has_many :unconformities, dependent: :destroy
  
end

app/models/corrective_action.rb
class CorrectiveAction < ActiveRecord::Base
  validates :name, :description, presence: true
	validates_length_of :description, maximum: 200

	belongs_to :unconformity
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :member_roles
end

app/models/member_role.rb
class MemberRole < ActiveRecord::Base
  belongs_to :member
  belongs_to :role
  belongs_to :team
  has_many :projects, through: :team
end

app/models/pratice.rb
class Pratice < ActiveRecord::Base
  has_many :pratices_procedures, dependent: :destroy
  has_many :procedures, through: :pratices_procedures
end

app/models/pratices_procedure.rb
class PraticesProcedure < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :pratice
  has_many :pratices_procedures_projects
  has_many :projects, through: :pratices_procedures_project
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  validates :name, :description, presence:true
  
  has_many :pratices_procedures, dependent: :destroy
  accepts_nested_attributes_for :pratices_procedures,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :pratices, through: :pratices_procedures
  accepts_nested_attributes_for :pratices,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :procedures_projects
end

app/models/procedures_project.rb
class ProceduresProject < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :client, :date_ready, :description, presence:true
  has_many :audits,  dependent: :destroy
  has_one :team , dependent: :destroy
  accepts_nested_attributes_for :team
  
  has_one :procedures_project, dependent: :destroy
  accepts_nested_attributes_for :procedures_project,
  reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :member_roles
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :project
  has_many :member_roles, dependent: :destroy
  has_many :members, through: :member_roles
  has_many :roles, through: :member_roles
  
  accepts_nested_attributes_for :member_roles,
  reject_if: :all_blank, allow_destroy: true
  
end

app/models/unconformity.rb
class Unconformity < ActiveRecord::Base
  validates :name, :description, presence:true
  belongs_to :audit
  has_one :corrective_action, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_team
  before_action :set_member_role
  before_action :set_pratices_procedures
  before_action :set_procedures
  before_action :set_procedures_project
  
  
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end
  
  def index_audit
    @projects = Project.all
  end
  
  def index_unconformities
    @projects = Project.all
  end
  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.all.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    @team = @project.team
    @project.build_team
    @procedures_project = @project.procedures_project
    @project.build_procedures_project
    set_procedures
    set_member
    set_role
    
  end

  # GET /projects/1/edit
  def edit
    set_procedures
    set_member
    set_role
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "#{@project.name} criado com sucesso." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "#{@project.name} atualizado com sucesso."}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "#{@project.name} deletado com sucesso."}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end
    
    def set_team
      @team = Team.all
    end
    
    def set_member_role
      @member_role = MemberRole.all
    end
    
    def set_member
      @member = Member.all
    end
    
    def set_role
      @role = Role.all
    end
    
    def set_procedures_project
      @procedures_project = ProceduresProject.all
    end
    
    def set_pratices_procedures
      @pratices_procedures = PraticesProcedure.all
    end
    
    def set_procedures
      @procedures = Procedure.all
    end
    
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :client, :description, :date_ready, :initial_date, 
      team_attributes: [:id, :name, :project_id, :_destroy, member_roles_attributes: [:id, :team_id, :member_id, :role_id, :_destroy]],
      procedures_project_attributes:[:id, :project_id,:procedure_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pratices_helper.rb
module PraticesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/projects/_form.html.erb
	<%= form_for(@project) do |f| %>
	<%= render '/layouts/errors', object: @project %>
	
		<div class="form-group">
			<%= f.label :Nome %></br>
			<%= f.text_field :name, class:"form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :Cliente %></br>
			<%= f.text_field :client , class:"form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :Data_de_início %></br>
			<%= f.date_select :initial_date, class:"form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :Data_de_entrega %></br>
			<%= f.date_select :date_ready, class:"form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :Descrição %></br>
			<%= f.text_area :description, class:"form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :Defina_o_processo %> </br>
			<%= f.fields_for :procedures_project do |pp_fields| %>
				<%= pp_fields.collection_select(:procedure_id, @procedures, :id, :name) %>
			<%end%>
		</div>
	
		<%= f.fields_for :team do |team_fields| %>
			<div class="form-group">
				<%= team_fields.label :Nome_da_equipe_do_projeto %></br>
				<%= team_fields.text_field :name, class:"form-control"%>
			</div>
			<div class="member_roles">
				<table class="table">
					<tr>
						<td width=100><%= team_fields.label :Membro %></td>
						<td width=100><%= team_fields.label :Papél %></td>
					</tr>
				</table>
				
				<div id="member-roles">
					<%= team_fields.fields_for :member_roles do |member_roles_fields| %>
						<% render partial: "member_role_fields", locals: { f: member_roles_fields } %>
					<%end%>
					<p title="Adicionar membro"><%= link_to_add_association(" ", team_fields, :member_roles,  class:'glyphicon glyphicon-plus') %></p>
				</div>
			</div>
			</br>
		<%end%>
	
		<%= f.submit class:'btn btn-primary' %>
		<%= link_to 'Cancelar', root_path, class:'btn btn-default' %>
	<%end%>

app/views/projects/_member_role_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<table class="table">
			<tr>
				<td width=500><%= f.collection_select(:member_id, @member, :id,:name) %></td>
				<td width=500><%= f.collection_select(:role_id, @role.order(:name), :id, :name)%></td>
				<td><p title="Remover"><%= link_to_remove_association('', f, class:'glyphicon glyphicon-remove') %></p></td>
			</tr>	
		</table>
	</div>
</div>

app/views/projects/edit.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading"><h2><%= "Editando #{@project.name}"%></h2></div>
  <div class="panel-body">
    <%= render 'form'%>
  </div>
</div>
</div>

app/views/projects/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="pagee-header"><%= pluralize(@projects.size, "Projeto", "Projetos") %> 
				<small class="novo_projeto"><%= link_to new_project_path, class:'btn btn-default' do %> Novo Projeto
				<%end%></small>
			</h1>
		</div>
	</div>
	
	<% @projects.each do |project| %>
		<div class="hide_show">
			<div class="row">
				<div class="col-md-7">
					<h3>
						<p><%= link_to project.name , project%></p>
					</h3>
				</div>
			</div>
			<hr>
		</div>
		
<% end %>
</div>

app/views/projects/index_audit.html.erb
<div class="container">
	<% @projects.each do |project| %>
		<div class="hide_show">
			<div class="row">
				<div class="col-md-7">
					<p><h2><%= link_to project.name , project%> <%= link_to 'Nova auditoria', new_project_audit_path(project), class: 'btn-xs btn-primary' %></p></h2>
						<% project.audits.each do |audit| %>
						<p>&nbsp
  						<% if audit.completed == "Sim" %>
  							<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-success' %>
  						<% elsif audit.completed == "Não" %>
  							 <%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-danger' %>
  						<% else %>
  						  <%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-default' %>
  						<%end%>
  						<small class='atalho'><%= audit.datetime%> às <%= audit.schedule.to_formatted_s(:time)%>hrs</small>
  					</p>
  					<%end%>
				</div>
			</div>
			<hr>
		</div>
		
  <%end%>
</div>

app/views/projects/index_rascunho.html.erb
<div class="container">
	<% @projects.each do |project| %>
			<div class="row">
				<div class="col-md-7">
					<p><h2><%= link_to project.name , project%> <small><%= pluralize(project.audits.size, "Auditoria","Auditorias")%></small></h2></p>
					
							<% project.audits.order(:identification).each do |audit| %>
							  <center>
									<% if audit.completed == "Sim" %>
										<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-success' %>
									<% elsif audit.completed == "Não" %>
										<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-danger' %>
									<% else %>
										<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-default' %>
									<%end%>
								</center>
	    					</br>
	    					<% if audit.unconformities.size > 0 %>
	    						<% audit.unconformities.each do |unconformity| %>
	        					<h4><%= link_to unconformity.name , project_audit_unconformity_path(project, audit, unconformity), class:'navbar-brand'%></h4>
	        						 
	          					<% if unconformity.corrective_action.present? %>
		          					<% if unconformity.corrective_action.completed == "Sim" %>
													<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-success' %> &nbsp
												<% elsif unconformity.corrective_action.completed == "Não" %>
													<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-danger' %>	
												<% else %>
													<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-default' %>
												<%end%>
											<%else%>
								  			<%= link_to 'Criar ação corretiva', new_project_audit_unconformity_corrective_action_path(project, audit, unconformity), class: 'btn btn-primary' %></td>
								  		<%end%>
								  <%end%>
	          		<%else%>
	          			<small>Não possui Não Conformidades</small>
	          		<%end%>
	          	<%end%>
				</div>
			</div>
			<hr>
		</div>
  <%end%>
</div>

class="table table-hover table-condensed"

app/views/projects/index_unconformities.html.erb
<div class="container">
	<div class="center">
		<div class="col-lg-12">
			<% @projects.each do |project| %>
					<h2><%= link_to project.name , project%> <small><%= pluralize(project.audits.size, "Auditoria","Auditorias")%></small></h2>
					<div class="table-responsive">
						<table style="text-align:center; width:75%;" class="table table-hover table-condensed table-bordered">
							<tr><td><h4>Auditorias</td></h4><td><h4>Não Conformidades</td></h4><td><h4>Ação Corretiva</td></tr></h4>
							
								<% project.audits.order(:identification).each do |audit| %>
								<tr>
									<td>
										<% if audit.completed == "Sim" %>
											<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-success' %>
										<% elsif audit.completed == "Não" %>
											<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-danger' %>
										<% else %>
											<%= link_to audit.identification, project_audit_path(project, audit), class: 'btn btn-default' %>
										<%end%>
									</td>
										<% if audit.unconformities.size > 0 %>
										<td align=middle>
			    						<% audit.unconformities.each do |unconformity| %></br>
			    						<div class='row'>
			    							<%= link_to unconformity.name , project_audit_unconformity_path(project, audit, unconformity), class: 'btn btn-default'%>
			    						</div>
			    						
			        				<%end%>
			        			</td>
			        			<%else%>
			        			<td align=middle>
			          			<small>Não possui Não Conformidades</small>
			          		</td>
			          		<%end%>
			          		<td align=middle>
			          			<% audit.unconformities.each do |unconformity| %></br>
			          			<div class='row'>
				          			<% if unconformity.corrective_action.present? %>
			          					<% if unconformity.corrective_action.completed == "Sim" %>
														<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-success' %> &nbsp
													<% elsif unconformity.corrective_action.completed == "Não" %>
														<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-danger' %>	
													<% else %>
														<%= link_to unconformity.corrective_action.name, project_audit_unconformity_corrective_action_path(project, audit, unconformity, unconformity.corrective_action), class: 'btn btn-default' %>
													<%end%>
												<%else%>
									  			<%= link_to 'Criar ação corretiva', new_project_audit_unconformity_corrective_action_path(project, audit, unconformity), class: 'btn btn-primary' %>
									  		<%end%>
									  	</div>
										  <%end%>
										 </td>
			          </tr>
								<%end%>
						</table>
					</div>
			<%end%>
		</div>
	</div>
</div>

app/views/projects/new.html.erb
<div class='container'>
  <div class="panel panel-default">
    <div class="panel-heading"><h2>Criar Projeto</h2></div>
    <div class="panel-body">
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
	<div class="jumbotron">
		<article>
			<header>
				<h1><%= @project.name %></h1>
			</header>
			<hr>
			<h2>Cliente</h2>
				<p><%= @project.client %></p>
			<h3>Data de Início</h3>
				<p><%= @project.initial_date %></p>
			<hr>
			<h3>Data de Entrega</h3>
				<p><%= @project.date_ready %></p>
			<hr>
			<div class="panel panel-default">
			  <div class="panel-body">
					<p><%=simple_format @project.description%></p>
				</div>
			</div>
			<hr>
			<h3>Processo</h3>
				<%= link_to @project.procedures_project.procedure.name, procedure_path(@project.procedures_project.procedure) %>
			<h3><b><%="Equipe #{@project.team.name}" %></h3></b>
			
			<table class="table">
				<tr>
					<td><h4><b>Membros</b></h4></td>
					<td><h4><b>Papél</b></h4></td>
				</tr>
				<% @project.team.member_roles.each do |members| %>
					<tr>
						<td><%= members.member.name %></td>
						<td><%= members.role.name %></td>
					</tr>
				<%end%>
			</table>
			
			<hr>
		</article>
		 <%= link_to pluralize(@project.audits.size, "Auditoria","Auditorias"), project_audits_path(@project) %>
	</div>
		 <%= link_to projects_path, class:'btn btn-link' do %>
		 <i class="glyphicon glyphicon-home">Projetos</i>
		 	<%end%>

		 	<%= link_to edit_project_path(@project), class:'btn btn-link' do %>
		 <i class="glyphicon glyphicon-edit">Editar</i>
		 	<%end%>

		 	<%= link_to project_path(@project),method: :delete, data:{ confirm: "Deseja deletar este projetot?"}, class:'btn btn-link' do %>
		 <i class="glyphicon glyphicon-remove-sign">Deletar projeto</i>
		 	<%end%>
 </div>