config/routes.rb
Rails.application.routes.draw do
  resources :procedures_projects
  resources :pratices_procedures
  resources :pratices
  resources :procedures
  get 'home/index'
  root 'home#index'
  resources :member_roles
  resources :teams
  resources :roles
  resources :members
  resources :projects do
      collection do
        get 'index_audit'
        get 'index_unconformities'
      end
    resources :audits do
     resources :unconformities do
       resources :corrective_actions
     end
    end
  end
  
  

end

app/models/audit.rb
class Audit < ActiveRecord::Base
    validates :identification, :description, :datetime, :schedule, presence:true
	KIND = %w(Produto Processo)
	validates_inclusion_of :kind, in: KIND
  belongs_to :projetc
  has_many :unconformities, dependent: :destroy
  
end

app/models/corrective_action.rb
class CorrectiveAction < ActiveRecord::Base
  validates :name, :description, presence: true
	validates_length_of :description, maximum: 200

	belongs_to :unconformity
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :member_roles
end

app/models/member_role.rb
class MemberRole < ActiveRecord::Base
  belongs_to :member
  belongs_to :role
  belongs_to :team
  has_many :projects, through: :team
end

app/models/pratice.rb
class Pratice < ActiveRecord::Base
  has_many :pratices_procedures, dependent: :destroy
  has_many :procedures, through: :pratices_procedures
end

app/models/pratices_procedure.rb
class PraticesProcedure < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :pratice
  has_many :pratices_procedures_projects
  has_many :projects, through: :pratices_procedures_project
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  validates :name, :description, presence:true
  
  has_many :pratices_procedures, dependent: :destroy
  accepts_nested_attributes_for :pratices_procedures,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :pratices, through: :pratices_procedures
  accepts_nested_attributes_for :pratices,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :procedures_projects
end

app/models/procedures_project.rb
class ProceduresProject < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :client, :date_ready, :description, presence:true
  has_many :audits,  dependent: :destroy
  has_one :team , dependent: :destroy
  accepts_nested_attributes_for :team
  
  has_one :procedures_project, dependent: :destroy
  accepts_nested_attributes_for :procedures_project,
  reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :member_roles
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :project
  has_many :member_roles, dependent: :destroy
  has_many :members, through: :member_roles
  has_many :roles, through: :member_roles
  
  accepts_nested_attributes_for :member_roles,
  reject_if: :all_blank, allow_destroy: true
  
end

app/models/unconformity.rb
class Unconformity < ActiveRecord::Base
  validates :name, :description, presence:true
  belongs_to :audit
  has_one :corrective_action, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :set_pratices_procedures
  
  

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
    @pratice = Pratice.new
    @pratices_procedures = @procedure.pratices_procedures
    @procedure.pratices_procedures.build
    set_pratice
  end

  # GET /procedures/1/edit
  def edit
    set_pratice
    
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.html { redirect_to @procedure, notice: 'Procedure was successfully created.' }
      else
        format.html { render :new }
        
      end
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Procedure was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: 'Procedure was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end
    
    def set_pratices_procedures
      @pratice_procedure = PraticesProcedure.all
    end
    
    def set_pratice
      @pratice = Pratice.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:name, :description, 
      pratices_procedures_attributes: [:id, :pratice_id, :procedure_id, :_destroy],
      pratices_attributes: [:id, :name, :description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pratices_helper.rb
module PraticesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/procedures/_form.html.erb
  <%= form_for([@procedure]) do |f| %>
  <%= render '/layouts/errors', object: @procedure %>
  
    <div class="form-group">
      <%= f.label :Nome %><br>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :Descrição %><br>
      <%= f.text_area :description, class:"form-control"%>
    </div>
    
      <%= f.label :Prática %>
  			<div id="pratices_procedure">
            <%= f.fields_for :pratices_procedures do |pp_fields| %>
               <% render partial: 'pratices_procedure_fields', locals: { f: pp_fields } %>
            <%end%>
            <%= link_to_add_association('Selecionar', f, :pratices_procedures,  class:'glyphicon glyphicon-plus') %>
         </div>
         <div id="pratices">
            <% f.fields_for :pratices do |pratices_fields| %>
               <%= render partial: 'pratice_fields', locals: {f: pratices_fields} %>
            <%end%>
            </br>
            <%= link_to_add_association('Criar', f, :pratices,  class:'glyphicon glyphicon-plus') %>
         </div>
      </br>
      <%= f.submit class:'btn btn-primary' %>
      <%= link_to 'Cancelar', procedures_path(@procedure), class:'btn btn-default' %>
  <%end%>

app/views/procedures/_pratice_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<table class="table">
			<tr>
			  
				<div class="form-group">
      <%= f.label :Nome %>&nbsp<%= link_to_remove_association('', f, class:'glyphicon glyphicon-remove') %><br>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Descrição %><br>
      <%= f.text_area :description, class:"form-control"%>
    </div>
			</tr>	
		</table>
	</div>
</div>

app/views/procedures/_pratices_procedure_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<table class="table">
			<tr>
				<td><%= f.collection_select(:pratice_id, @pratice.order(:name), :id,:name,prompt: true) %></td>
				<td><%= link_to_remove_association('', f, class:'glyphicon glyphicon-remove') %></td>
			</tr>	
		</table>
	</div>
</div>

app/views/procedures/edit.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading"><h2><%= "Editando #{@procedure.name}"%></h2></div>
      <div class="panel-body">
        <%= render 'form'%>
      </div>
  </div>
</div>

app/views/procedures/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="pagee-header"><%= pluralize(@procedures.size, "Processo", "Processos") %> 
				<small class="novo_projeto"><%= link_to new_procedure_path, class:'btn btn-default' do %> Novo Processo
				<%end%></small>
			</h1>
		</div>
	</div>

	<% @procedures.each do |procedure| %>
		<div class="row">
			<div class="col-md-7">
				<h3>
					<p><%= link_to procedure.name , procedure%></p>
				</h3>
			</div>
		</div>
		<hr>

<% end %>
</div>

app/views/procedures/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading"><h2>Criar Processo</h2></div>
      <div class="panel-body">
        <%= render 'form'%>
      </div>
  </div>
</div>

app/views/procedures/show.html.erb
<div class="container">
	<div class="jumbotron">
		<article>			
			<header>
				<h1><%= @procedure.name %></h1> 			
			</header>
			<hr>
				<div class="panel-body">
					<h3>Descrição</h3>
						<div class="panel panel-default">
							<p style= "text-align: justify;"><%= simple_format @procedure.description%></p>
						</div>
				</div>
		</article>
		<table class="table">
			<tr>
				<td><h4><b>Práticas</b></h4></td>
				<td><h4><b>Descrição</b></h4></td>
			</tr>
			<% @procedure.pratices_procedures.order(:pratice_id).each do |pratice| %>
				<tr>
					<td><%= pratice.pratice.name %></td>
					<td><%= pratice.pratice.description %></td>
				</tr>
			<%end%>
		</table>
		<hr>
		<%= link_to edit_procedure_path(@procedure), class:'btn btn-default' do %>
		 		<i class="glyphicon glyphicon-edit">Editar</i>
			<%end%>

		<%= link_to "Deletar Processo", procedure_path(@procedure),method: :delete, data:{ confirm: "Deseja deletar este Processo?"}, class:'btn btn-default'%>
		
		<%= link_to "Votlar", procedures_path(@procedure), class:'btn btn-default'%>
	</div>
 </div>