config/routes.rb
Rails.application.routes.draw do
  resources :procedures_projects
  resources :pratices_procedures
  resources :pratices
  resources :procedures
  get 'home/index'
  root 'home#index'
  resources :member_roles
  resources :teams
  resources :roles
  resources :members
  resources :projects do
      collection do
        get 'index_audit'
        get 'index_unconformities'
      end
    resources :audits do
     resources :unconformities do
       resources :corrective_actions
     end
    end
  end
  
  

end

app/models/audit.rb
class Audit < ActiveRecord::Base
    validates :identification, :description, :datetime, :schedule, presence:true
	KIND = %w(Produto Processo)
	validates_inclusion_of :kind, in: KIND
  belongs_to :projetc
  has_many :unconformities, dependent: :destroy
  
end

app/models/corrective_action.rb
class CorrectiveAction < ActiveRecord::Base
  validates :name, :description, presence: true
	validates_length_of :description, maximum: 200

	belongs_to :unconformity
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :member_roles
end

app/models/member_role.rb
class MemberRole < ActiveRecord::Base
  belongs_to :member
  belongs_to :role
  belongs_to :team
  has_many :projects, through: :team
end

app/models/pratice.rb
class Pratice < ActiveRecord::Base
  has_many :pratices_procedures, dependent: :destroy
  has_many :procedures, through: :pratices_procedures
end

app/models/pratices_procedure.rb
class PraticesProcedure < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :pratice
  has_many :pratices_procedures_projects
  has_many :projects, through: :pratices_procedures_project
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  validates :name, :description, presence:true
  
  has_many :pratices_procedures, dependent: :destroy
  accepts_nested_attributes_for :pratices_procedures,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :pratices, through: :pratices_procedures
  accepts_nested_attributes_for :pratices,
  reject_if: :all_blank, allow_destroy: true
  
  has_many :procedures_projects
end

app/models/procedures_project.rb
class ProceduresProject < ActiveRecord::Base
  belongs_to :procedure
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :client, :date_ready, :description, presence:true
  has_many :audits,  dependent: :destroy
  has_one :team , dependent: :destroy
  accepts_nested_attributes_for :team
  
  has_one :procedures_project, dependent: :destroy
  accepts_nested_attributes_for :procedures_project,
  reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :member_roles
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :project
  has_many :member_roles, dependent: :destroy
  has_many :members, through: :member_roles
  has_many :roles, through: :member_roles
  
  accepts_nested_attributes_for :member_roles,
  reject_if: :all_blank, allow_destroy: true
  
end

app/models/unconformity.rb
class Unconformity < ActiveRecord::Base
  validates :name, :description, presence:true
  belongs_to :audit
  has_one :corrective_action, dependent: :destroy
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pratices_helper.rb
module PraticesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-warning" role="alert">
	<ul>
		<% object.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>
</div>
<%end%>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
	<div class= "container">
		<div class="alert alert-success alert-dismissible" role="alert">
  			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  			<%= flash[:notice] %>
		</div>
	</div>

	<% elsif flash[:alert] %>
	<div class= "container">
		<div class="alert alert-danger alert-dismissible" role="alert">
  			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  			<%= flash[:alert] %>
		</div>
	</div>
<%end%>

app/views/layouts/_footerIndex.html.erb
<footer class="footer">
	<div class="container">
		<p class="text-muted">Maturidade e Agilidade - AgileQA.</p>
	</div>
</footer>

app/views/layouts/_headerIndex.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('AQbrand.png', size:'30', alt:'AgileQA'), root_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Projetos', projects_path %></li>
          <li><%= link_to 'Membros', members_path %></li>
          <li><%= link_to 'Papéis', roles_path %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to 'Processos', procedures_path %></li>
          <li><%= link_to 'Práticas', pratices_path %></li>
          
          <li class="divider-vertical"></li>
          <li><%= link_to 'Auditorias', index_audit_projects_path %></li>
          <li><%= link_to 'Não Conformidades', index_unconformities_projects_path %></li>
        </ol>
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agileqa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render 'layouts/headerIndex' %>

<%= render 'layouts/flash' %>

<%= yield %>

<%= render 'layouts/footerIndex' %>

</body>
</html>